import { Experience, Stat } from "../types";

export const experiences: Experience[] = [
  {
    id: "exp1",
    title: "Senior Full Stack Developer",
    company: "TechCorp Solutions",
    location: "San Francisco, CA",
    duration: "2022 - Present",
    description: [
      "Lead development of scalable web applications using React, Node.js, and AWS",
      "Mentor junior developers and conduct code reviews",
      "Architected microservices infrastructure serving 1M+ users",
      "Implemented CI/CD pipelines reducing deployment time by 70%",
    ],
    skills: ["React", "Node.js", "AWS", "TypeScript", "Docker", "MongoDB"],
    achievements: [
      "Increased application performance by 60%",
      "Led team of 5 developers",
      "Delivered 15+ successful projects",
    ],
  },
  {
    id: "exp2",
    title: "Full Stack Developer",
    company: "StartupXYZ",
    location: "Austin, TX",
    duration: "2020 - 2022",
    description: [
      "Developed and maintained multiple client-facing applications",
      "Collaborated with design team to implement pixel-perfect UIs",
      "Optimized database queries improving response time by 40%",
      "Built RESTful APIs serving mobile and web applications",
    ],
    skills: ["Vue.js", "Python", "PostgreSQL", "Redis", "GraphQL"],
    achievements: [
      "Reduced bug reports by 45%",
      "Built 3 products from scratch",
      "Improved code coverage to 85%",
    ],
  },
  {
    id: "exp3",
    title: "Frontend Developer",
    company: "Digital Agency",
    location: "Remote",
    duration: "2018 - 2020",
    description: [
      "Created responsive websites for diverse client portfolio",
      "Implemented modern JavaScript frameworks and libraries",
      "Collaborated with backend developers on API integration",
      "Maintained legacy codebases and performed upgrades",
    ],
    skills: ["JavaScript", "HTML5", "CSS3", "Sass", "jQuery", "Bootstrap"],
    achievements: [
      "Delivered 25+ client projects",
      "Achieved 98% client satisfaction",
      "Reduced load times by 50%",
    ],
  },
  {
    id: "exp4",
    title: "Frontend Developer Intern",
    company: "Gency",
    location: "Remote",
    duration: "2012 - 2014",
    description: [
      "Created responsive websites for diverse client portfolio",
      "Implemented modern JavaScript frameworks and libraries",
      "Collaborated with backend developers on API integration",
      "Maintained legacy codebases and performed upgrades",
      "Created responsive websites for diverse client portfolio",
      "Implemented modern JavaScript frameworks and libraries",
      "Collaborated with backend developers on API integration",
      "Maintained legacy codebases and performed upgrades",
      "Created responsive websites for diverse client portfolio",
      "Implemented modern JavaScript frameworks and libraries",
      "Collaborated with backend developers on API integration",
      "Maintained legacy codebases and performed upgrades",
      "Created responsive websites for diverse client portfolio",
      "Implemented modern JavaScript frameworks and libraries",
      "Collaborated with backend developers on API integration",
      "Maintained legacy codebases and performed upgrades",
      "Created responsive websites for diverse client portfolio",
      "Implemented modern JavaScript frameworks and libraries",
      "Collaborated with backend developers on API integration",
      "Maintained legacy codebases and performed upgrades",
      "Created responsive websites for diverse client portfolio",
      "Implemented modern JavaScript frameworks and libraries",
      "Collaborated with backend developers on API integration",
      "Maintained legacy codebases and performed upgrades",
      "Created responsive websites for diverse client portfolio",
      "Implemented modern JavaScript frameworks and libraries",
      "Collaborated with backend developers on API integration",
      "Maintained legacy codebases and performed upgrades",
      "Created responsive websites for diverse client portfolio",
      "Implemented modern JavaScript frameworks and libraries",
      "Collaborated with backend developers on API integration",
      "Maintained legacy codebases and performed upgrades",
    ],
    skills: ["JavaScript", "HTML5", "CSS3", "Sass", "jQuery", "Bootstrap"],
    achievements: [
      "Delivered 25+ client projects",
      "Achieved 98% client satisfaction",
      "Reduced load times by 50%",
    ],
  },
];

export const experienceStats: Stat[] = [
  { label: "Years Experience", value: "5+" },
  { label: "Projects Completed", value: "50+" },
  { label: "Technologies Mastered", value: "20+" },
  { label: "Coffee Consumed", value: "∞" },
];
