export const ClassEffectForSyncAndStyle = [
  { word: "•", className: "" },
  { word: "Developed", className: "" },
  { word: "dynamic", className: "text-xl text-purple" },
  { word: "outfit", className: "text-xl text-purple" },
  { word: "recommendation", className: "text-xl text-purple" },
  { word: "algorithm", className: "text-xl text-purple" },
  { word: "operating", className: "" },
  { word: "on", className: "" },
  { word: "OpenAI", className: "text-red-400" },
  { word: "APIs", className: "text-red-400" },
  { word: "tailored", className: "" },
  { word: "to", className: "" },
  { word: "user", className: "" },
  { word: "preferences", className: "" },
  { word: "•", className: "" },
  { word: "Spearheaded", className: "" },
  { word: "the", className: "" },
  { word: "development", className: "" },
  { word: "of", className: "" },
  { word: "an", className: "" },
  { word: "inventory", className: "text-xl text-purple" },
  { word: "scraper,", className: "text-xl text-purple" },
  { word: "maintaining", className: "" },
  { word: "120,000+", className: "text-xl text-purple" },
  { word: "merchandise", className: "text-xl text-purple" },
  { word: "from", className: "" },
  { word: "60+", className: "text-xl text-purple" },
  { word: "retailers", className: "text-xl text-purple" },
  { word: "using", className: "" },
  { word: "hidden", className: "" },
  { word: "RESTful", className: "text-red-400" },
  { word: "APIs", className: "text-red-400" },
  { word: "and", className: "" },
  { word: "HTML", className: "text-red-400" },
  { word: "parsing", className: "text-red-400" },
  { word: "web", className: "text-red-400" },
  { word: "scraping", className: "text-red-400" },
  { word: "methods,", className: "" },
  { word: "maintaining", className: "" },
  { word: "up-to-date", className: "text-xl text-purple" },
  { word: "inventory", className: "text-xl text-purple" },
  { word: "•", className: "" },
  { word: "Developed", className: "" },
  { word: "APIs", className: "text-red-400" },
  { word: "with", className: "" },
  { word: "Node.js,", className: "text-red-400" },
  { word: "Express", className: "text-red-400" },
  { word: "and", className: "" },
  { word: "TypeScript", className: "text-red-400" },
  { word: "for", className: "" },
  { word: "authentication,", className: "text-xl text-purple" },
  { word: "outfit", className: "text-xl text-purple" },
  { word: "recommendations,", className: "text-xl text-purple" },
  { word: "and", className: "" },
  { word: "inventory", className: "text-xl text-purple" },
  { word: "•", className: "" },
  { word: "Oversaw", className: "" },
  { word: "Vercel", className: "text-red-400" },
  { word: "deployments,", className: "text-xl text-purple" },
  { word: "conducted", className: "" },
  { word: "code", className: "text-xl text-purple" },
  { word: "reviews,", className: "text-xl text-purple" },
  { word: "maintained", className: "" },
  { word: "codebase", className: "text-xl text-purple" },
  { word: "and", className: "" },
  { word: "collaborated", className: "" },
  { word: "with", className: "" },
  { word: "testing", className: "text-xl text-purple" },
  { word: "team", className: "" },
];
export const ClassEffectForASU = [
  { word: "•", className: "" },
  { word: "Engineered", className: "" },
  { word: "a", className: "" },
  { word: "gamification", className: "text-xl text-purple" },
  { word: "of", className: "" },
  { word: "Canvas", className: "text-red-400" },
  { word: "LMS", className: "text-red-400" },
  { word: "using", className: "" },
  { word: "React,", className: "text-red-400" },
  { word: "TypeScript,", className: "text-red-400" },
  { word: "and", className: "" },
  { word: "MongoDB,", className: "text-red-400" },
  { word: "featuring", className: "" },
  { word: "course-specific", className: "text-xl text-purple" },
  { word: "leaderboards,", className: "text-xl text-purple" },
  { word: "virtual", className: "text-xl text-purple" },
  { word: "shops,", className: "text-xl text-purple" },
  { word: "and", className: "" },
  { word: "currency", className: "text-xl text-purple" },
  { word: "management,", className: "text-xl text-purple" },
  { word: "resulting", className: "" },
  { word: "in", className: "" },
  { word: "a", className: "" },
  { word: "25%", className: "text-xl text-purple" },
  { word: "increase", className: "text-xl text-purple" },
  { word: "in", className: "" },
  { word: "student", className: "text-xl text-purple" },
  { word: "engagement", className: "text-xl text-purple" },
  { word: "•", className: "" },
  { word: "Designed", className: "" },
  { word: "and", className: "" },
  { word: "implemented", className: "" },
  { word: "a", className: "" },
  { word: "real-time", className: "text-xl text-purple" },
  { word: "notification", className: "text-xl text-purple" },
  { word: "system", className: "text-xl text-purple" },
  { word: "using", className: "" },
  { word: "Socket.io", className: "text-red-400" },
  { word: "accommodating", className: "" },
  { word: "10,000+", className: "text-xl text-purple" },
  { word: "students", className: "text-xl text-purple" },
  { word: "•", className: "" },
  { word: "Optimized", className: "text-xl text-purple" },
  { word: "application", className: "" },
  { word: "using", className: "" },
  { word: "React", className: "text-red-400" },
  { word: "Developer", className: "text-red-400" },
  { word: "Tools", className: "text-red-400" },
  { word: "and", className: "" },
  { word: "implemented", className: "" },
  { word: "caching,", className: "text-xl text-purple" },
  { word: "debouncing", className: "text-xl text-purple" },
  { word: "and", className: "" },
  { word: "lazy", className: "text-xl text-purple" },
  { word: "loading", className: "text-xl text-purple" },
];

export const ClassEffectForEmipro = [
  { word: "•", className: "" },
  { word: "Composed", className: "" },
  { word: "Stored", className: "text-xl text-purple" },
  { word: "Procedures", className: "text-xl text-purple" },
  { word: "in", className: "" },
  { word: "PostgreSQL", className: "text-red-400" },
  { word: "for", className: "" },
  { word: "predictive", className: "" },
  { word: "cash", className: "" },
  { word: "flow", className: "" },
  { word: "by", className: "" },
  { word: "analyzing", className: "text-xl text-purple" },
  { word: "historical", className: "text-xl text-purple" },
  { word: "financial", className: "text-xl text-purple" },
  { word: "data", className: "" },
  { word: "•", className: "" },
  { word: "Developed", className: "" },
  { word: "a", className: "" },
  { word: "dynamic", className: "" },
  { word: "configuration", className: "" },
  { word: "system", className: "" },
  { word: "using", className: "" },
  { word: "Python,", className: "text-red-400" },
  { word: "React", className: "text-red-400" },
  { word: "to", className: "" },
  { word: "optimize", className: "" },
  { word: "cash", className: "" },
  { word: "flow", className: "" },
  { word: "analysis", className: "" },
];

export const ClassEffectForSetu = [
  { word: "•", className: "" },
  { word: "Secured", className: "" },
  { word: "an", className: "" },
  { word: "80%", className: "text-xl text-purple" },
  { word: "reduction", className: "text-xl text-purple" },
  { word: "in", className: "" },
  { word: "discrepancies", className: "text-xl text-purple" },
  { word: "and", className: "" },
  { word: "enhanced", className: "text-xl text-purple" },
  { word: "inventory", className: "text-xl text-purple" },
  { word: "transfer", className: "text-xl text-purple" },
  { word: "accuracy", className: "text-xl text-purple" },
  { word: "by", className: "" },
  { word: "developing", className: "" },
  { word: "robust", className: "" },
  { word: "Inventory", className: "text-xl text-purple" },
  { word: "Count", className: "text-xl text-purple" },
  { word: "system", className: "text-xl text-purple" },
  { word: "using", className: "" },
  { word: "Python,", className: "text-red-400" },
  { word: "React", className: "text-red-400" },
  { word: "simplifying", className: "" },
  { word: "inventory", className: "" },
  { word: "systems", className: "" },
  { word: "for", className: "" },
  { word: "over", className: "" },
  { word: "100+", className: "text-xl text-purple" },
  { word: "enterprise", className: "text-xl text-purple" },
  { word: "warehouses", className: "text-xl text-purple" },
  { word: "•", className: "" },
  { word: "Engineered", className: "" },
  { word: "a", className: "" },
  { word: "customer", className: "text-xl text-purple" },
  { word: "segmentation", className: "text-xl text-purple" },
  { word: "system", className: "text-xl text-purple" },
  { word: "using", className: "" },
  { word: "RFM", className: "text-red-400" },
  { word: "analysis,", className: "" },
  { word: "processing", className: "" },
  { word: "100,000+", className: "text-xl text-purple" },
  { word: "customer", className: "" },
  { word: "records", className: "" },
  { word: "with", className: "" },
  { word: "Python", className: "text-red-400" },
  { word: "and", className: "" },
  { word: "PostgreSQL", className: "text-red-400" },
  { word: "stored", className: "" },
  { word: "procedures,", className: "" },
  { word: "enabling", className: "" },
  { word: "targeted", className: "text-xl text-purple" },
  { word: "marketing", className: "text-xl text-purple" },
  { word: "campaigns,", className: "text-xl text-purple" },
  { word: "increasing", className: "" },
  { word: "customer", className: "" },
  { word: "retention", className: "" },
  { word: "by", className: "" },
  { word: "60%", className: "text-xl text-purple" },
  { word: "•", className: "" },
  { word: "Extended", className: "" },
  { word: "manufacturing", className: "text-xl text-purple" },
  { word: "software", className: "text-xl text-purple" },
  { word: "with", className: "" },
  { word: "interactive", className: "text-xl text-purple" },
  { word: "component", className: "text-xl text-purple" },
  { word: "hierarchy", className: "text-xl text-purple" },
  { word: "visualization", className: "text-xl text-purple" },
  { word: "interface", className: "text-xl text-purple" },
  { word: "using", className: "" },
  { word: "React", className: "text-red-400" },
  { word: "•", className: "" },
  { word: "Integrated", className: "" },
  { word: "Shopify,", className: "text-red-400" },
  { word: "WooCommerce", className: "text-red-400" },
  { word: "with", className: "" },
  { word: "ERP", className: "text-red-400" },
  { word: "system", className: "" },
  { word: "utilizing", className: "" },
  { word: "Webhooks", className: "text-red-400" },
  { word: "and", className: "" },
  { word: "REST", className: "text-red-400" },
  { word: "APIs", className: "text-red-400" },
];
export const slugs = [
  "typescript",
  "javascript",
  "java",
  "react",
  "html5",
  "css3",
  "nodedotjs",
  "express",
  "nextdotjs",
  "prisma",
  "amazonaws",
  "postgresql",
  "firebase",
  "nginx",
  "vercel",
  "jest",
  "cypress",
  "docker",
  "git",
  "jira",
  "github",
  "gitlab",
  "visualstudiocode",

  "tailwind",

  "mongodb",
  "python",
  "flask",

  "unity",
  "prisma",
  "reactredux",
  "jwt",
  "socketio",
  "restapi",

  "googlecloud",
  "gmail",
];
